### PR TITLE
Extention Tracker Support for AWS S3

### PR DESCRIPTION
**Pull request by AtulRajput01**
**AWS S3: Add Master Tracker Extension Support for AWS S3**

This PR addresses issue #10  Add Master Tracker for Extension Support for AWS S3. The changes include:

- Enabled efficient tracking and management of S3 buckets within the WarpSQL project.
- Empowered users to leverage AWS S3 capabilities for storing and retrieving data.
- Modified the docker-compose.yml file to include necessary configurations for AWS S3 integration.
- Added new services and environment variables to enable extension tracker functionality with AWS S3.
- Updated the project's README.md file to provide detailed instructions for AWS S3 integration.
- Added a dedicated section that explains the configuration steps and setup guidelines for enabling extension tracker support with AWS S3.

Please review the changes and consider merging them into the main branch. Thank you!

### CODE REVIEW

**Comment by singhalkarun** [comment]
Hey @AtulRajput01, I see lot of other commits which are not associated with the current issue. Please remove all other commits from this PR so that it will be easier for us to review the changes.

Here are steps you should follow to avoid that in future as well,

1) Fork the repo
2) Create a new branch out of main branch for the specific issue
3) Commit and push all changes associated with that issue on that branch
4) Raise a PR to be merged into main branch of original repo

Thanks.

**Comment by jayanth-kumar-morem** [comment]
@AtulRajput01 Please squash multiple commits with the same commit message and also add smoketests to test the AWS S3 support.
Also, before raising a PR, please check whether the GHA are passing in your forked repo.
Thanks!

**Comment by AtulRajput01** [comment]
> @AtulRajput01 Please squash multiple commits with the same commit message and also add smoketests to test the AWS S3 support. Also, before raising a PR, please check whether the GHA are passing in your forked repo. Thanks!

hii @jayanth-kumar-morem could you please review my PR.

**Comment by AtulRajput01** [comment]
hii @ChakshuGautam  Could you please take a look and provide your feedback?

**Comment by ChakshuGautam** [comment]
Hey @AtulRajput01 I see the @jayanth-kumar-morem 's comments are still not resolved. Can you please take a look at those?

**Pull request closed without merging**
