### PR TITLE
[CI] Fix failing workflow for bitnami

### PR DESCRIPTION
**Pull request by PiyushRaj927**
Version mismatch causing workflow failure: https://github.com/Samagra-Development/WarpSQL/actions/runs/5133893971/jobs/9237125480#step:3:5382.
1. updated PostGIS version for Bitnami image

### CODE REVIEW

**Comment by jayanth-kumar-morem** [comment]
Hi @PiyushRaj927 , The CI is passing in this commit 5faa6fcc26e7d6d2325c096f47ffeb145a2e2b65 . You are updating the PostGIS version from `3.2` to `3.3` which is well and good. Just want to check in with what `pgdg110` corresponds to, because if its corresponds to pg11, this version `3.3.3+dfsg-1~exp1.pgdg110+1` is not accepted as of now because we are specifically running the smoketests for pg15.

**Comment by jayanth-kumar-morem** [comment]
If we can't rely on PostGIS apt repo, I think its best we can get Postgis official source tarball releases here http://postgis.net/source/ and install it manually.

**Comment by PiyushRaj927** [comment]
Agreed. Can we merge this as a temporary fix until we implement the suggested approach mentioned earlier

**Comment by jayanth-kumar-morem** [comment]
@ChakshuGautam , we are installing PostGIS from apt repo now, which can be considered as a temporary fix for GHA. Later if we encounter a similar issue with PostGIS, we need to definitely consider installing PostGIS from sources / official PostGIS repo. 

+1 Merge it as a temporary fix

**Pull request merged**
